# Generated by Django 4.1.4 on 2023-05-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_notification_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_product',
            new_name='title',
        ),
    ]
