# Generated by Django 4.1.4 on 2023-05-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_product',
            field=models.CharField(default=1, max_length=255, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Вид продукта'),
        ),
    ]
