# Generated by Django 4.1.4 on 2023-05-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_name_product_alter_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
