# Generated by Django 4.1.4 on 2023-05-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcart',
            old_name='guest',
            new_name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_quantity',
            field=models.IntegerField(default=0, verbose_name='Итоговое количество товара'),
        ),
    ]
